spring:
  application:
    name: t1

  datasource:
    url: jdbc:postgresql://localhost:5432/techradar
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      naming:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
  error:
    include-message: always